version: "3.4"
services:
  react-app:
    image: react-app
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - service-link
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    image: api-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - service-link
    depends_on: 
      - mongo
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
  mongo: 
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - service-link
    volumes:
      - mongo-data:/data/db
networks:
  service-link:
    driver: bridge
volumes:
  mongo-data:
    driver: local