POST http://localhost:5000/bookings/add HTTP/1.1

Content-Type: application/json
{
    "FirstName": "Sebastian",
    "LastName" : "Narloch", 
    "BookingWith" : "James",
    "BookingDate" : "10/21/2021",
    "BookingTime" : "10:00"
}