POST http://localhost:5000/bookings/add HTTP/1.1
content-type: application/json

{
    "FirstName": "Sebastian",
    "LastName": "Narloch", 
    "BookingWith": "James",
    "BookingDate": "2021-10-21",
    "BookingTime": "11:00"
}

###
GET http://localhost:5000/bookings/
